---
- name: OSX Local Provisioner
  hosts: local
  sudo: no
  vars_prompt:
    # for App Store
    - name: appstore_id
      prompt: "App StoreのIDを入力してください"
      private: no
    - name: appstore_password
      prompt: "App Storeのパスワードを入力してください"
      private: no
  roles:
    # App Installations
    - brew
      #- defaults
    - mas
    - brew-cask

    # Configurations
    # - karabiner
    # - git
    # - vim
    # - xcode
